//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForeignExchange.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForeignExchange.Resources.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter a numeric value to convert ... !!!.
        /// </summary>
        public static string AmountNumericValidation {
            get {
                return ResourceManager.GetString("AmountNumericValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter a value in amount...!!!.
        /// </summary>
        public static string AmountValidation {
            get {
                return ResourceManager.GetString("AmountValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear.
        /// </summary>
        public static string ComandClear {
            get {
                return ResourceManager.GetString("ComandClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Convert.
        /// </summary>
        public static string CommandConvert {
            get {
                return ResourceManager.GetString("CommandConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amount:.
        /// </summary>
        public static string LabelAmount {
            get {
                return ResourceManager.GetString("LabelAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Source Rate:.
        /// </summary>
        public static string LabelSourceRate {
            get {
                return ResourceManager.GetString("LabelSourceRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Target Rate:.
        /// </summary>
        public static string LabelTargetRate {
            get {
                return ResourceManager.GetString("LabelTargetRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter amout to convert...!!!.
        /// </summary>
        public static string PlaceHolrderAmount {
            get {
                return ResourceManager.GetString("PlaceHolrderAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select source rate...!!!.
        /// </summary>
        public static string SourceRateValidation {
            get {
                return ResourceManager.GetString("SourceRateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select target rate...!!!.
        /// </summary>
        public static string TargetRateValidation {
            get {
                return ResourceManager.GetString("TargetRateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Foreign Exchange.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please, check your connection internet...!!!.
        /// </summary>
        public static string TitleAccessInternet {
            get {
                return ResourceManager.GetString("TitleAccessInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a in.
        /// </summary>
        public static string TitleIn {
            get {
                return ResourceManager.GetString("TitleIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a is equal to:.
        /// </summary>
        public static string TitleIsEqual {
            get {
                return ResourceManager.GetString("TitleIsEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Load rates, plase wait...!!!.
        /// </summary>
        public static string TitleLoadRate {
            get {
                return ResourceManager.GetString("TitleLoadRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ready to convert...!!!.
        /// </summary>
        public static string TitleReadyConvert {
            get {
                return ResourceManager.GetString("TitleReadyConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please, check your internet settings...!!!.
        /// </summary>
        public static string TitleSettingsInternet {
            get {
                return ResourceManager.GetString("TitleSettingsInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select source rate...!!!.
        /// </summary>
        public static string TitleSourceRate {
            get {
                return ResourceManager.GetString("TitleSourceRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rate loaded from internet...!!!.
        /// </summary>
        public static string TitleStatusInternet {
            get {
                return ResourceManager.GetString("TitleStatusInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select target source...!!!.
        /// </summary>
        public static string TitleTargetRate {
            get {
                return ResourceManager.GetString("TitleTargetRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The amount:.
        /// </summary>
        public static string TitleTheAmount {
            get {
                return ResourceManager.GetString("TitleTheAmount", resourceCulture);
            }
        }
    }
}
